apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
    - image: nginx
      name: s3-test-container
      securityContext:
        privileged: true
      volumeMounts:
        - name: mntdatas3fs
          mountPath: /var/s3:shared
  volumes:
    - name: mntdatas3fs
      hostPath:
        # mounted a subdirectory from the s3 host node
        path: /mnt/data-s3fs/subdirectory